/* eslint-disable no-unused-vars */
export enum MessageService {
  GET_ATTRIBUTE_ALL= 0x01,
  GET_ATTRIBUTE_SINGLE= 0x0e,
  RESET= 0x05,
  START= 0x06,
  STOP= 0x07,
  CREATE= 0x08,
  DELETE= 0x09,
  MULTIPLE_SERVICE_PACKET= 0x0a,
  APPLY_ATTRIBUTES= 0x0d,
  SET_ATTRIBUTE_SINGLE= 0x10,
  FIND_NEXT= 0x11,
  READ_TAG= 0x4c,
  WRITE_TAG= 0x4d,
  READ_TAG_FRAGMENTED= 0x52,
  WRITE_TAG_FRAGMENTED= 0x53,
  READ_MODIFY_WRITE_TAG= 0x4e
};
